### ISSUE TITLE
[Unit1][Create your first Android app] 관련 질문입니다.  

### ISSUE THREAD

**Issue by Frogfromspace** [gdgand/ComposeCamp2022-for-Beginners#10]
## 질문 내용
- 깃허브에 접속하여 url을 복사하였습니다.
- 그 이후 컴퓨터에 폴더를 생성 후 cmd를 실행하였고 그 상태에서 git clone url을 입력 시 오류가 납니다.
- 추가 설명을 요청드립니다.

## 코드랩 링크
- 해당 코드랩 페이지 링크를 넣어주세요. 
- 질문을 파악하는데에 도움이 될만한 링크가 추가로 있다면 같이 넣어주세요. 
- https://github.com/Frogfromspace/ComposeCamp2022-for-Beginners/tree/main
- 
![image](https://user-images.githubusercontent.com/116716313/200233868-779fb24b-06dc-48b7-b5f4-df3b7a16e9ce.png)

## 스크린샷 또는 코드 스니펫 
- 작업 중인 코드를 첨부합니다. 
![image](https://user-images.githubusercontent.com/116716313/200233669-9b0227c3-0911-4ac7-975c-80cd7cfffa8d.png)

## 올리기 전 체크사항 
- [x] 기존에 같은 질문이 있었는지 확인했습니다. 
- [x] Label 을 맞게 설정했습니다.

**Comment by JaesungLeee** [comment]
안녕하세요. Compose Camp 비기너코스 캠핑지기 이재성입니다.
올려주신 스니펫을 확인해보니 Git이 설치되어있지 않은 것으로 보입니다.
Git 설치를 우선적으로 하신 후 진행하시면 될 것 같습니다.

**Comment by Frogfromspace** [comment]
기본적인 질문이지만 git은 어떻게 설치해야하나요? 이번 과정에 제공되는 메뉴얼이 있나요?

**Comment by yeoncheong** [comment]
안녕하세요. Compose Camp 비기너코스 캠핑지기 황연진입니다.
깃과 깃허브 사용에 관한 매뉴얼은 메일로 보내드린 캠핑장 주소로 접속하시어, Unit 0 영상을 참고하시면 좋을 것 같습니다.
깃 설치에 대한 내용은 따로 없으므로 구글에서 깃 설치방법에 대해 찾아보거나 [공식 홈페이지](https://git-scm.com/downloads)에서 OS에 맞는 버전의 깃을 다운받으시는 것이 좋을 것 같습니다.

**Comment by Frogfromspace** [comment]
제공해주신 공식 홈페이지에서 설치하였습니다. 감사합니다.

**Comment by yeoncheong** [comment]
한 주 당 하나의 Unit 이수를 권장하므로 이번주는 Unit 0 : 깃허브 사용 방법을 다루는 주차이며, 당장 이번주부터 코드랩을 바로 시작하고 싶으시다면 Unit1로 이동하는 것이 맞습니다.
다만 코드랩 실습을 진행할 때 Unit 폴더보다는 **Pathway 폴더 내부에 있는 안드로이드 프로젝트**를 오픈하시기 바랍니다.

**Comment by hhyeok1026** [comment]
https://opentutorials.org/course/3837

**Comment by JaesungLeee** [comment]
해결된 질문으로 판단되어 close합니다.
