### ISSUE TITLE
[Unit1][Create your first Android app] 관련 질문입니다.  

### ISSUE THREAD

**Issue by hr4861-park** [gdgand/ComposeCamp2022-for-Beginners#11]
## 질문 내용

코드랩에 있는대로 하드코딩 문자열을 추출하고 있습니다.
코드랩의 내용대로면 추출시 `stringResource(R.string.happy_birthday_text)` 로 추출이 되는데요.
제 PC에서 진행해보니 `getString(R.string.happy_birthday_text)`로 추출이 됨을 확인했습니다.

`stringResource` 를 호출하나, `getString` 을 호출하나, 둘다 정상동작함은 확인하였는데요.

두 함수간의 동작에 차이가 있는지요?

## 코드랩 링크

https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#7

## 스크린샷 또는 코드 스니펫 
```kotlin
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            HappyBirthdayTheme {
                Surface(color = MaterialTheme.colors.background) {
                    BirthDayGreetingWithImage(
                        getString(R.string.happy_birthday_text),
                        getString(R.string.signature_text)
                    )
                }
            }
        }
    }
}
```

## 올리기 전 체크사항 
- [x] 기존에 같은 질문이 있었는지 확인했습니다. 
- [x] Label 을 맞게 설정했습니다.

**Comment by hr4861-park** [comment]
추가로 label이 `question`, `unit1` 로 고정되어 수정할수가 없네요. 확인부탁드리겠습니다.

**Comment by yeoncheong** [comment]
안녕하세요. Compose Camp 비기너코스 캠핑지기 황연진입니다.

Compose가 출시되기 전에는 context의 `getString()` 메소드로 문자열을 로딩할 경우, context 속의 resource가 있어야 로딩이 가능하기 때문에 context에 대한 관리가 별도로 필요한데요. 이 때, context를 외부로 넘길 경우 **메모리가 누수되는 문제가 발생**할 수 있습니다.

`
    @Composable
    @ReadOnlyComposable
    fun stringResource(@StringRes id: Int): String {
	    val resources = resources()
	    return resources.getString(id)
    }
`

따라서 Compose에서는 `getString()` 메소드를 감싼 문자열 로딩 메소드 `stringResource()` 를 사용합니다. `resources()` 라는 메소드가 **resources라는 객체 안에서 context를 관리**해주기 때문에 사용하는 사람이 context를 신경쓰지 않아도 됩니다.

라벨은 오른쪽 Labels 단에서 필요없는 라벨을 x로 지우고 다른 라벨을 선택하시면 되겠습니다.

**Comment by hr4861-park** [comment]
> 안녕하세요. Compose Camp 비기너코스 캠핑지기 황연진입니다.
> 
> Compose가 출시되기 전에는 context의 `getString()` 메소드로 문자열을 로딩할 경우, context 속의 resource가 있어야 로딩이 가능하기 때문에 context에 대한 관리가 별도로 필요한데요. 이 때, context를 외부로 넘길 경우 **메모리가 누수되는 문제가 발생**할 수 있습니다.
> 
> ```
> @Composable
> @ReadOnlyComposable
> fun stringResource(@StringRes id: Int): String {
>     val resources = resources()
>     return resources.getString(id)
> }
> ```
> 
> 따라서 Compose에서는 `getString()` 메소드를 감싼 문자열 로딩 메소드 `stringResource()` 를 사용합니다. `resources()` 라는 메소드가 **resources라는 객체 안에서 context를 관리**해주기 때문에 사용하는 사람이 context를 신경쓰지 않아도 됩니다.
> 
> 라벨은 오른쪽 Labels 단에서 필요없는 라벨을 x로 지우고 다른 라벨을 선택하시면 되겠습니다.

자세한 설명 감사드립니다.

라벨의 경우 collaborator 들만 수정가능한 상태가 아닌가 싶은데요. 
저 외에 다른분들 보고 계시다면 확인좀 부탁드리겠습니다.

질문에 대한 궁금증은 해소되어 이슈는 close 하겠습니다.

**Comment by Sanghun-Lee** [comment]
저도 이슈업하려고하는데 라벨 수정이 안되네요 ㅠㅠ

**Comment by yeoncheong** [comment]
라벨 관련해서 답변 드립니다.
라벨은 Admin 권한이 있는 사람들만 변경이 가능합니다.
그래서 방금 이슈 템플릿에서 이슈 관련 문항을 삭제했습니다.
이슈 작성하실 때 라벨은 신경 안 쓰셔도 될 것 같습니다. 😄
