### ISSUE TITLE
[Unit2][앱에 버튼 추가] 관련 질문입니다.  

### ISSUE THREAD

**Issue by Sanghun-Lee** [gdgand/ComposeCamp2022-for-Beginners#13]
## 질문 내용
Unit2의 Pathway2, Pathway3의 코드들이 모두 작성되어있는데, 새로 프로젝트를 만들어서 PR 올려야하나요.

## 코드랩 링크
- https://developer.android.com/courses/pathways/android-basics-compose-unit-2-pathway-2
- [Pathway2 Dice Roller MainActivity 소스코드](https://github.com/gdgand/ComposeCamp2022-for-Beginners/blob/main/Unit2/Pathway2/basic-android-kotlin-compose-training-dice-roller/app/src/main/java/com/example/diceroller/MainActivity.kt)
- [Pathway2 연습 클릭동작 MainActivity 소스코드](https://github.com/gdgand/ComposeCamp2022-for-Beginners/blob/main/Unit2/Pathway2/basic-android-kotlin-compose-training-lemonade/app/src/main/java/com/example/lemonade/MainActivity.kt)
- [Pathway3 팁 계산기 MainActivity 소스코드](https://github.com/gdgand/ComposeCamp2022-for-Beginners/blob/main/Unit2/Pathway3/basic-android-kotlin-compose-training-tip-calculator/app/src/main/java/com/example/tiptime/MainActivity.kt)

## 스크린샷 또는 코드 스니펫 
- 없습니다.

## 올리기 전 체크사항 
- [X] 기존에 같은 질문이 있었는지 확인했습니다. 

- 라벨이 변경되지않아 Unit1으로 작성하였습니다.

**Comment by yeoncheong** [comment]
안녕하세요. Compose Camp 비기너코스 캠핑지기 황연진입니다.
Unit2 Pathway2와 Pathway3의 코드랩은 참여자분들이 직접 안드로이드 프로젝트를 생성해서 진행하는 코드랩이기 때문에 깃허브에 정답 코드가 작성되어 있습니다.
코드랩을 보고 새로 프로젝트를 생성해주시면 되겠습니다.
깃허브의 정답 코드는 참고용으로 사용해주세요.

**Comment by Sanghun-Lee** [comment]
네네 확인 감사합니다. 답변이되어 이슈 클로즈하겠습니다~
