### ISSUE TITLE
[Unit0][Git 사용하기] 관련 질문입니다.  

### ISSUE THREAD

**Issue by Frogfromspace** [gdgand/ComposeCamp2022-for-Beginners#15]
## 질문 내용
- Git사용하기를 통해서 진행하고 있습니다.
- System UI Isn't responding이라는 에러 메시지가 뜨며 실행되지 않네요.
- 어떤 문제가 있을까요?
## 코드랩 링크
- 해당 코드랩 페이지 링크를 넣어주세요. 
- 질문을 파악하는데에 도움이 될만한 링크가 추가로 있다면 같이 넣어주세요. 

## 스크린샷 또는 코드 스니펫 
- 작업 중인 코드를 첨부합니다. 

![image](https://user-images.githubusercontent.com/116716313/200977782-36a37b21-9a4c-473d-939d-c40dce8d4b06.png)

## 올리기 전 체크사항 
- [ ] 기존에 같은 질문이 있었는지 확인했습니다.

**Comment by yeoncheong** [comment]
안녕하세요. Compose Camp 비기너코스 캠핑지기 황연진입니다.
애뮬레이터의 System UI isn't responding 문구는 빌드가 실패한 것이 아닌 컴퓨터 자체의 용량 부족, 컴퓨터의 성능 저하로 인한 경고문이라고 보시면 될 것 같습니다.
만약 빌드가 실패한다면 안드로이드 스튜디오 왼쪽아래 Build 탭에서 빨간 글씨로 오류문구가 올라오게 됩니다.
실행이 완전히 완료될 때까지 기다려보시는 것이 좋을 것 같습니다.
