### ISSUE TITLE
[Unit1][매개변수 Modifier] 관련 질문입니다.  

### ISSUE THREAD

**Issue by zkzkzhzj** [gdgand/ComposeCamp2022-for-Beginners#16]
## 질문 내용
- Codelab 과정을 진행하던 중 항상 함수의 매개변수로 Modifier 를 받는 것을 확인하였습니다.
- 제가 생각하기엔 공통된 Modifier 속성값이 있다면 최상위에 만들어두고 해당 객체를 넘겨받아 사용하면 좋겠지만 중복되는 속성값이 없더라도 매개변수로 받는 것이 이로운지에 대한 의문이 들었습니다.
- 최상위에 속성값 없는 val modifier = Modifier 를 하나 만들고 그걸 계속해서 매개변수로 넘겨주어 재사용하는 방식이 권장되는 방식일까요? 
- 중복되는 속성값이 없다면 매개변수로 두지 않고 그때그때 생성하여 사용하지만 중복되는 바로 윗단계에서 만들고 넘겨주는게 이로운걸까요?
- 질문이 옳지 않다면 바로 삭제하도록 하겠습니다.

## 코드랩 링크
- https://developer.android.com/codelabs/basic-android-kotlin-compose-business-card?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-business-card#0
- 상단 코드랩 진행하며 의문이 들었습니다.

## 스크린샷 또는 코드 스니펫 
````kotlin
@Composable
fun BusinessCard(
    modifier: Modifier
) {
    Column() {
        Column(
            modifier = modifier.weight(7f)
        ) {
            BusinessCardTop(
                modifier = modifier
            )
        }

        Column(
            modifier = modifier.weight(3f)
        ) {
            BusinessCardInfo(
                modifier = modifier
            )
        }
    }
}
// 위 처럼 중복되는 값이 없더라도 최상단에서 val modifier = Modifier 객체를 넘겨주어 계속해서 재사용할 것인지

// 아니라면 아래처럼 중복되지 않을경우 매개변수로 받지 않고 그때 그때 생성해서 주고 중복되는 함수 윗단계에서 만들고 넘겨줄 것인지
@Composable
fun BusinessCard(
) {
    Column() {
        Column(
            modifier = Modifier.weight(7f)
        ) {
            BusinessCardTop(
            )
        }

        Column(
            modifier = Modifier.weight(3f)
        ) {
            val paddingModifier = Modifier
                .padding(start = 48.dp, top = 8.dp, bottom = 8.dp)
            BusinessCardInfo(
                modifier = paddingModifier
            )
        }
    }
}
// CardInfo 내부
@Composable
fun BusinessCardInfo(
    modifier: Modifier
) {
    Column {
        Column(
            modifier = modifier
        ) {
            BusinessCardInfoText(
            )
        }
        Column(
            modifier = modifier
        ) {
            BusinessCardInfoText(
            )
        }
        Column(
            modifier = modifier
        ) {
            BusinessCardInfoText(
            )
        }
    }
}
````

## 올리기 전 체크사항 
- [ O ] 기존에 같은 질문이 있었는지 확인했습니다.

**Comment by taehwandev** [comment]
올려주신 코드의 Modifier는 적절한 방법이 아닙니다.

`fun BusinessCard(
    modifier: Modifier
) {
    Column() {
        Column(
            modifier = modifier.weight(7f)
        ) {
            BusinessCardTop(
                modifier = modifier
            )
        }

        Column(
            modifier = modifier.weight(3f)
        ) {
            BusinessCardInfo(
                modifier = modifier
            )
        }
    }
} `

이렇게 하시면 modifier 의 속성을 외부에서 변경 시 모든 ui에 동일한 옵션이 적용됩니다.

Modifier는 그냥 객체를 생성하고 이걸 이용한 레이아웃의 뷰의 배경을 설정하거나 shape를 설정하거나 클릭을 처리합니다. 말그대로 뷰 별로 뷰의 속성을 말합니다.
이를 위 코드처럼 활용하시면 이미 적절한 UI가 노출되지 않습니다.
현재야 별 옵션이 없어서 그냥 넘어가겠지만

뷰 별로 설정을 추가할때마다 새로운 객체가 아니기때문에 옵션을 이어서 그대로 merge 합니다.

내부 코드를 살펴보시면 모두 다른 옵션을 제공해줌을 알 수 있습니다.

이는 객체로서의 옵션으로 접근하셔야 합니다.

**Comment by zkzkzhzj** [comment]
앗. 감사합니다
그렇다면 말씀하신 내용이 최상단에 속성값없는 의미없는 modifier 를 주어 넘겨주어 변수처럼 사용하는것 보단 말그대로 옵션의 의미로 중복된다면 만들어 넘겨주면 좋겠지만 그때 그때 생성하는게 좋다는 말씀이 맞으실까요?

**Comment by taehwandev** [comment]
보통 함수에 넘겨주는 Modifier는 해당 코드 내의 최상위 컨테이너에 대한 Modifier를 외부에서 추가로 정의 가능함을 말합니다.
만약 이를 수정하지 않도록 하려면 Modifier를 넘겨주지 않도록 만드시면 됩니다.
참고로 모든 코드에서 Modifier를 외부 주입하지 않아도 내부에서 새로운 Modifier를 생성하여 사용합니다.

참고로 이정도의 메모리는 유의미 하지 않습니다. 정말 필요한 부분의 메모리를 줄이는것이 최적화입니다. 이정도의 메모리는 필요한 부분에 대한 메모리일 뿐…

**Comment by zkzkzhzj** [comment]
바보같은 고민을 하고있었네요ㅜ.ㅜ
감사합니다! CS공부의 부족함을 느끼네요 하하
