### ISSUE TITLE
[Unit1][Android Studio] 관련 질문입니다.  

### ISSUE THREAD

**Issue by langmal** [gdgand/ComposeCamp2022-for-Beginners#17]
## 질문 내용
- 안드로이드 스튜디오나 레포지토리 클론을 지우고 다시 받고를 여러 번 했는데도 어떤 점이 문제인지 안드로이드로 열리지 않는 것 같은데 이렇게 해도 진행이 잘 되는지 잘 몰라서 질문합니다. 

## 코드랩 링크
- 해당 코드랩 페이지 링크를 넣어주세요. 
- 질문을 파악하는데에 도움이 될만한 링크가 추가로 있다면 같이 넣어주세요. 

## 스크린샷 또는 코드 스니펫 
![화면 캡처 2022-11-12 082003](https://user-images.githubusercontent.com/108164439/201443437-eab06b5e-20f9-4ee8-bae9-77fb4668051c.png)

## 올리기 전 체크사항 
- [x] 기존에 같은 질문이 있었는지 확인했습니다.

**Comment by yeoncheong** [comment]
안녕하세요. Compose Camp 비기너코스 캠핑지기 황연진입니다.
프로젝트를 여실 때 Unit 폴더가 아닌, Unit 폴더 내의 Pathway 내의 Codelab 파일(ex. /Unit1/Pathway3/BirthdayCard)을 오픈해주시면 되겠습니다.

**Comment by JaesungLeee** [comment]
해결된 질문으로 판단되어 close합니다.
https://github.com/gdgand/ComposeCamp2022-for-Beginners/issues/10#issuecomment-1306395529

**Comment by haeun11** [comment]
> 안녕하세요. Compose Camp 비기너코스 캠핑지기 황연진입니다. 프로젝트를 여실 때 Unit 폴더가 아닌, Unit 폴더 내의 Pathway 내의 Codelab 파일(ex. /Unit1/Pathway3/BirthdayCard)을 오픈해주시면 되겠습니다.

안녕하세요. 저는 Unit 파일로 열면 괜찮은데 코드랩 파일로 열면 오류가 생깁니다. 혹시 어떻게 해야 할까요?
![image](https://user-images.githubusercontent.com/89173772/202974453-9f49f746-8a48-44fa-91f1-69fe6561f29f.png)
![image](https://user-images.githubusercontent.com/89173772/202974528-105f44fe-0a41-4f02-bce4-ef67b8899c64.png)

**Comment by yeoncheong** [comment]
해당 사진만으로는 저희가 오류를 파악하기 어렵습니다.
상단 Build -> Clean Project 한번 해보시고 여전히 오류가 발생한다면 오류 사진을 첨부해서 issue 새로 작성 부탁드립니다.
