### ISSUE TITLE
[Unit2] Pathway3의 Calculating Tip섹션에서 번역 오류가 있습니다.

### ISSUE THREAD

**Issue by ukhyun2402** [gdgand/ComposeCamp2022-for-Beginners#18]
### 영문버전
![image](https://user-images.githubusercontent.com/38240148/201471787-4453d1c6-4079-4b4b-8588-79afad8df693.png)

### 한글버전
![image](https://user-images.githubusercontent.com/38240148/201471788-464a953b-d3ba-4580-89ae-5fb99a361576.png)

한글버전 내에서는 FocusManage를 Compasable함수인 EditNumberFiled에 넣으려고 하고 있으나 영어버전에서는 그 상위 Composable 함수인 TipTimeScreen에 넣으라고 기재되어 있습니다.

**Comment by JaesungLeee** [comment]
넵 감사합니다.
해당 이슈는 오픈채팅방에도 공유하고 close하겠습니다.

**Comment by ukhyun2402** [comment]
혹시 이런 번역 오류 관련해서도 계속해서 올려도 괜찮은건가요?

**Comment by JaesungLeee** [comment]
본래 Issue 탭은 질문에 대한 질의응답으로 사용할 계획이었습니다.
가급적 오픈채팅방을 이용하여 공유해주신다면 감사하겠습니다.
감사합니다.
