### ISSUE TITLE
Unit2 ArtSpace 관련 질문입니다.

### ISSUE THREAD

**Issue by hr4861-park** [gdgand/ComposeCamp2022-for-Beginners#19]
`Art Space` 코드랩 진행중에 있습니다.

코드랩 본문에 간략한 내용만 있는데요.

실습에 진행할 이미지나 텍스트는 임의로 사용해도 괜찮을까요?

코드랩 주소는 아래와 같습니다.

https://developer.android.com/codelabs/basic-android-kotlin-compose-art-space?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-art-space#0

**Comment by JaesungLeee** [comment]
네 가능합니다.
