### ISSUE TITLE
Modifier 적용 순서에 대한 질문입니다.

### ISSUE THREAD

**Issue by ukhyun2402** [gdgand/ComposeCamp2022-for-Beginners#20]
## 질문 내용
- Modifer에 적용 순서에 관한 질문입니다.
- 단순 CSS처럼 생각했는데, 제 생각대로 UI가 구성되지 않아 Modifier에 관해 찾아보니 다음과 같은 글이 있어서 아무리 고민해봐도 이해가 되지않아 질문드립니다.

![image](https://user-images.githubusercontent.com/38240148/201510121-fc3edcf3-c90c-4bf0-8009-ff71a63243a9.png)
[링크](https://stackoverflow.com/questions/62939473/how-to-add-margin-in-jetpack-compose)

Modifer는 어떻게 적용되고 순서는 어떠한 방향으로 적용되는 건가요?

## 올리기 전 체크사항 
- [O] 기존에 같은 질문이 있었는지 확인했습니다.

**Comment by hhyeok1026** [comment]
수정자 구글 문서 보게 되었는데, 참고하시면 될 것 같아서 링크 올립니다.
시간 날 때. 저 페이지 다 읽으면 좋을듯하네요.

// 수정자는 순서가 중요
https://developer.android.com/jetpack/compose/modifiers#order-modifier-matters

// 1,2 문단을 보면, 먼저 체인된 수정자가 먼저 적용. 
https://developer.android.com/jetpack/compose/modifiers#reusing-modifiers

**Comment by ukhyun2402** [comment]
그렇다면 css padding과는 좀 다르게 동작하는게 맞나보네요

css 에서는 margin border padding의 경계가 명확한 반면에 

compose에서는 그 의미가 조금은 다른 거 같습니다.

추가하면 저는 아무리봐도 밑에서부터 위로 이해하는게 좀 더 올바른 것 같다는 느낌은 지울수가없네요 ㅠㅠㅋㅋㅋㅋ

**Comment by dogdduddy** [comment]
확실히 여태의 padding과 border는 한 개체에 한 번씩만 적용했다보니 괴리감이 느껴지는 것 같습니다.
