### ISSUE TITLE
[Unit2][Tip Time] NumberFormat.getCurrencyInstance().format(tip) 관련 질문입니다.

### ISSUE THREAD

**Issue by ZungTa** [gdgand/ComposeCamp2022-for-Beginners#24]
## 질문 내용
- `calculateTip` 함수에서 사용하는 `NumberFormat.getCurrencyInstance().format(tip)` 부분이 예상대로 동작하지 않습니다.

## 코드랩 링크
- 해당 코드랩 페이지 링크를 넣어주세요. 
- 질문을 파악하는데에 도움이 될만한 링크가 추가로 있다면 같이 넣어주세요. 

[https://developer.android.com/codelabs/basic-android-kotlin-compose-calculate-tip?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-calculate-tip#5](https://developer.android.com/codelabs/basic-android-kotlin-compose-calculate-tip?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-calculate-tip#5)

## 스크린샷 또는 코드 스니펫 
```kt
private fun calculateTip(
    amount: Double,
    tipPercent: Double = 15.0,
    roundUp: Boolean
): String {
    var tip = tipPercent / 100 * amount

    if (roundUp)
        tip = kotlin.math.ceil(tip)

    return NumberFormat.getCurrencyInstance().format(tip)
}
```

![image](https://user-images.githubusercontent.com/43494803/202198070-3f2412a7-9af5-4e5a-8de0-db874c325b24.png)

`NumberFormat.getCurrencyInstance().format(tip)` 실행했을 때 소수점이 잘려서 나옵니다.

아예 그 함수 안에서
```kt
val tipa: Double = 46.331

val tipa2 = NumberFormat.getCurrencyInstance().format(tipa)

println("tipa2? $tipa2")
```
로 콘솔 찍어봐도 소수점 잘려서 나옵니다.
달라와 원화 차이인지 모르겠네요.

Kotlin Playground에서는 잘 작동합니다.

![image](https://user-images.githubusercontent.com/43494803/202198861-424108ad-41d4-4429-a019-d9f63c5b16fb.png)

## 올리기 전 체크사항 
- [x] 기존에 같은 질문이 있었는지 확인했습니다.

**Comment by hhyeok1026** [comment]
NumberFormat.getCurrencyInstance() 메서드가 
휴대폰내의 setting - 언어에 대해서 통화가 표시 되는 것 같아요

아마도 앱 내에서 통화를 달러로 고정 시키려면, 파라미터 locale이 있는 메서드를 쓰면 될 듯하네요
https://developer.android.com/reference/java/text/NumberFormat#getCurrencyInstance(java.util.Locale)


+ Q)
여기서 저도 추가적으로 궁금한게,
유닛 테스트 할 때도 원화로 표시가 되던데, 유닛 테스트에서는 어떻게 Default locale값을 가져오는지가 궁금하네요.
윈도우 세팅값을 자바에서 읽어오는 걸까요..?

**Comment by TreeJin99** [comment]
안녕하세요~ 유닛2 캠핑지기 남우진입니다. 위 hhyeok1026님께서 써주신 부분이 정답이 맞습니다!

` return NumberFormat.getCurrencyInstance().format(tip)`로 되어있던 부분 중  
getCurrencyInstance()에 들어갈 인자 값의 Default는 시스템의 locale로 맞춰있기 때문입니다.
예시:  `NumberFormat.getCurrencyInstance(Locale.getDefault()).format(price)`

이에 따라 다음 같이 getCurrencyInstance의 인자 값으로 'Locale.US'를 추가해주시면 해당 문제는 깔끔히 해결이 됩니다!
`  return NumberFormat.getCurrencyInstance(Locale.US).format(tip)`

추가적으로 Locale은 아래 스크린샷을 보시면 알 수 있듯이 JVM 인스턴스에 대한 Default Locale의 현재 값을 가져온다고 하네요! ㅎㅎ

<img width="792" alt="스크린샷 2022-11-17 오후 10 39 51" src="https://user-images.githubusercontent.com/90708425/202461240-7a9fdd30-3ff5-46af-be23-9ecbdfb4a18c.png">

**Comment by ZungTa** [comment]
감사합니다. 궁금증이 해결됐네요.
