### ISSUE TITLE
[Unit1] 코드랩 파일 실행 시 오류  

### ISSUE THREAD

**Issue by haeun11** [gdgand/ComposeCamp2022-for-Beginners#26]
## 질문 내용
- Pathway3에서 코드를 열었을 경우엔 오류가 나지 않는데, 하위에 있는 코드랩 파일을 열면 오류가 발생합니다.. 

## 코드랩 링크
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables#4

## 스크린샷 또는 코드 스니펫 
- 작업 중인 코드를 첨부합니다. 
- 
![image](https://user-images.githubusercontent.com/89173772/203214854-260eaa8e-75f7-499b-b1dd-c7e8edb97c8b.png)
![image](https://user-images.githubusercontent.com/89173772/203214918-4483c18d-3021-4a91-a391-6376e346d073.png)

## 올리기 전 체크사항 
- [x] 기존에 같은 질문이 있었는지 확인했습니다.

**Comment by JaesungLeee** [comment]
아래 이슈 확인 부탁드립니다.
https://github.com/gdgand/ComposeCamp2022-for-Beginners/issues/12#issue-1442120368

**Comment by dogdduddy** [comment]
HappyBirthdayTheme으로 작성해주셔야합니다!
기준이 package 이름 기준이라고 봐주시면 되겠습니다.

**Comment by haeun11** [comment]
수정해도 Greeting에서 여전히 Unsolved reference 메세지가 뜨는데 추가로 더 수정해야 할 부분이 있을까요?

**Comment by haeun11** [comment]
감사합니다 ㅠㅠ
